# -*- coding: utf-8 -*-
"""Twitter_Hashtag_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMCMGaqoF6y822VMkiQ9plfQ7J85xRUy
"""

import pandas as pd
pd.set_option('display.max_colwidth', None)

path = "/content/drive/MyDrive/dataset tweet/chatGPT.csv"

data = pd.read_csv(path)

data.head(10)

data.tail(8)

data.sample(4)

tweet_data = data.drop(['user_name', 'location'], axis=1)

tweet_data.head()

import re

"""# Hashtags"""

def collect_hashtags(tweet):
  hashtag = re.findall(r"#[a-zA-Z0-9]+", tweet)
  return ", ".join(hashtag)

tweet_data['hashtags'] = tweet_data['tweet'].apply(lambda x: collect_hashtags(x))

tweet_data.sample(5)

def count_hashtags(tweet):
  hashtag = re.findall(r"#[a-zA-Z0-9]+", tweet)
  return len(hashtag)

tweet_data['count_hashtags'] = tweet_data['tweet'].apply(lambda x: count_hashtags(x))

tweet_data.sample(5)

count = tweet_data['count_hashtags'].sum()
print(f"The number of hashtags: {count}")

all_hashtags = tweet_data['hashtags'].to_string()
all_hashtags_lst = re.findall(r"#\w+", all_hashtags)
all_hashtags_lst

hashtag_dict = {}
for i in all_hashtags_lst:
  if i in hashtag_dict:
    hashtag_dict[i] += 1
  else:
    hashtag_dict[i] = 1

hashtag_dict

sorted_hashtags = sorted(hashtag_dict.items(), key=lambda x: x[1], reverse=True)

sorted_hashtags

top_five_hashtags = sorted_hashtags[:5]
top_five_hashtags

# visualization
hashtags, count = zip(*top_five_hashtags)
print(hashtags)
print(count)

import matplotlib.pyplot as plt
plt.bar(hashtags, count)
plt.show()

"""# Sentiment analysis"""

from textblob import TextBlob

def get_sentiment(tweet):
  blob = TextBlob(tweet)
  return blob.sentiment.polarity

tweet_data['sentiment'] = tweet_data['tweet'].apply(lambda x: get_sentiment(x))

tweet_data.head()

def get_sentiment_label(score):
  if score > 0:
    return "positive"
  elif score < 0:
    return "negative"
  else:
    return "neutral"

tweet_data['sentiment_label'] = tweet_data['sentiment'].apply(lambda x: get_sentiment_label(x))

tweet_data.head()

count = tweet_data['sentiment_label'].value_counts()
print(count)

count.plot(kind='pie', autopct='%1.1f%%')
plt.show()

text = "GoingHomeTomorrow"
output = ""
for i in text:
  if i.isupper():
    output += " "
  output += i
print(output)